[package]
name = "progger"
version = "0.1.0"
authors = ["Jezza <jezzadabomb@gmail.com>"]
edition = "2018"

[dependencies.logos]
version = "0.11.4"
default-features = false

[dependencies.bumpalo]
version = "3.2.1"
features = ["collections"]
